name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v6

          - name: List Repo Files
            run: ls -la

          - name: Executing Shell script 
            run: ./ascii-script.sh
          
#          - name: Execute Cowsay CMD
#           run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

#          - name: Test File Exists
#           run: grep -i "dragon" dragon.txt

#          - name: Read File
#            run: cat dragon.txt

#          - name: List Repo Files
#            run: ls -la